pool:
  name: Default
  demands:
  - npm
  - java

steps:

- script: 'sudo  npm install --global '
  workingDirectory: WebUITesting
  displayName: 'npm install --global  copy'

- script: 'sudo npm install in current folder'
  workingDirectory: WebUITesting
  displayName: 'npm install in current folder'

- script: 'sudo npm install -g allure-commandline --save-dev'
  workingDirectory: WebUITesting
  displayName: 'npm install -g allure-commandline --save-dev'

- script: 'sudo npm install chromedriver@latest'
  workingDirectory: WebUITesting
  displayName: 'npm install chromedriver@latest'

- script: 'npx wdio wdio.conf.js'
  workingDirectory: TestAutomation/WebUITesting
  displayName: 'npx wdio wdio.conf.js'
  continueOnError: true





- bash: 'npm install chromedriver@latest'
  workingDirectory: WebUITesting
  displayName: 'npm install chromedriver@latest'
  enabled: false

- bash: 'sudo npx wdio wdio.conf.js'
  workingDirectory: WebUITesting
  displayName: 'npx wdio wdio.conf.js'
  continueOnError: true

- task: Molecula.allure-test-reports.allure-generate.AllureGenerate@1
  displayName: 'Generate Allure Report'
  inputs:
    resultsDir: 'WebUITesting/allure-results'
    targetDir: 'WebUITesting/allure-report/$(Build.BuildNumber)'

